
<br>

---
pagetitle: "Liyuan's personal website"
title: "Liyuan's personal website"
date: "Updated: `r format(Sys.Date())`"
---

<br>

## <font color="#DAAA00"> <font size=24x> </font>**Not everyone has the chance to study, so feel proud and lucky to learn!** ## {-}

<br> 

### <font color="#151100"> <font size=20x></font> Appreciated Learning Resources
<left> <font size=20x> </font>There are abudant resources online and in print for learning modeling, stasts, and coding in my perspective. Hopefully, this list can give you a hint and serve as a launching pad for some very useful website and talks.
<br>  

## {.tabset .tabset-fade}


### *Modeling resoures*

* [Community Land model-Microbe](https://github.com/email-clm/clm-microbe)
* [Millennial model](https://github.com/email-clm/Millennial)
* [Wetland Ecosystem Model](https://github.com/email-clm/WEM)
* [Community Terrestrial Systems Model](https://github.com/ESCOMP/ctsm)

### *R Lessons & Tutorials*

* [R Beyond Basics](https://github.com/dsidavis/RBeyondBasics)
* [Map time Davis](https://github.com/MicheleTobias/MaptimeDavis)
* [Mapping in R](https://ryanpeek.github.io/mapping-in-R-workshop/)
* [Data Carpentry: R and SQL](http://www.datacarpentry.org/R-ecology-lesson/05-r-and-databases.html)
* [Software Carpentry: **R for Reproducible Scientific Analysis**](http://data-lessons.github.io/gapminder-R/)
* [Data Carpentry: **R for Data Analysis and Visualization of Ecological Data**](http://www.datacarpentry.org/R-ecology-lesson/)
* [Data Carpentry: **Data Organization in Spreadsheets**](http://www.datacarpentry.org/spreadsheet-ecology-lesson/)
* [Data Carpentry: **Genomics Lesson**](https://jasonjwilliamsny.github.io/tidiness-genomics/)
* [ANGUS: **Analyzing High Throughput Sequencing Data; Exploratory RNAseq data analysis using RMarkdown**](http://angus.readthedocs.io/en/2017/index.html)
* [**RStudio Webinars**, many topics](https://www.rstudio.com/resources/webinars/)
* [**Coding Club**, great resource with many tutorials](https://ourcodingclub.github.io/)

#### *R eBooks/Courses*

* [Jenny Bryan's **Stat545.com**](http://stat545.com/)
* [Garrett Grolemund and Hadley Wickham's **R For Data Science**](http://r4ds.had.co.nz/)
* [Kieran Healy's **Data Visualization for Social Science**](http://socviz.co/)
* [Ethan White and Zack Brym's **Data Carpentry for Biologists**](http://www.datacarpentry.org/semester-biology/)
* [Chester Ismay and Albert Y. Kim's **Modern DiveR**](https://ismayc.github.io/moderndiver-book/)
* [Colin Gillespie and Robin Lovelace **Efficient R Programming**](https://csgillespie.github.io/efficientR/)
* [Julia Silge and David Robinson **Text Mining with R**](http://tidytextmining.com/)
* [Hadley Wickham's **Advanced R**](http://adv-r.had.co.nz/)

#### *Git/Github* 

* [Jenny Bryan's **Happy Git and Github for the useR**](http://happygitwithr.com/)
* [Coding Club **Intro to Github**](https://ourcodingclub.github.io/2017/02/27/git.html)
* [Martha Wohlfeil's **How to build a website**](https://marthazillig.github.io/2018-11-27-how-to-build-rmarkdown-website/)
* [Richard McElreath's ***Stat rethinking**](https://github.com/rmcelreath/rethinking)


### Presentations

* [Ryan Peek on using the `sf` package](https://youtu.be/taY6GrZ6vzE)
* [Rich Pauloo on using RMarkdown](https://youtu.be/CHBOVuo6RCo)
* [Kate Tiedeman tutorial on using `raster`](https://youtu.be/mHz4wxo-Q4U)
* [Clark Fitzgerald on integrating the shell with R](https://youtu.be/jgghG1K3740)
* [Myfanwy Johnston on unit testing (or code testing) in R](https://youtu.be/8G6bBum3O9A)
* [Michael Levy tutorial on using the `tidyverse`](https://youtu.be/9q7gssUP8UA)
* [Brandon Hurr "Intro to using `purrr`](http://d-rug.github.io/images/20171026/20171023_DRUG_map_walk.html#1)
* [Brandon Hurr "dplyr II: Joins and Set Operations"](http://d-rug.github.io/blog/2016/hurr-dplyr2)


<br>

